apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  name: wjms-wjmsjmswjms
  namespace: wjms-ns
  labels:
    weblogic.domainUID: wjms
spec:
  clusterName: WJMSjmsWJMS
  replicas: 1
---
apiVersion: weblogic.oracle/v1
kind: Cluster
metadata:
  name: wjms-wjmsjmscoco
  namespace: wjms-ns
  labels:
    weblogic.domainUID: wjms
spec:
  clusterName: WJMSjmsCOCO
  replicas: 1
---
apiVersion: weblogic.oracle/v9
kind: Domain
metadata:
  name: wjms
  namespace: wjms-ns
  labels:
    weblogic.domainUID: wjms
spec:
  domainUID: wjms
  domainHomeSourceType: FromModel
  image: container-registry.oracle.com/middleware/weblogic:14.1.2.0-generic-jdk17-ol8
  imagePullPolicy: IfNotPresent
  introspectVersion: '213'
  webLogicCredentialsSecret:
    name: wjms-weblogic-credentials
  domainHome: /u01/domains/wjms
  imagePullSecrets:
    - name: ocr
    - name: ocir
  # ===============================
  # Monitoring Exporter (SIDECAR)
  # ===============================
  monitoringExporter:
    image: ghcr.io/oracle/weblogic-monitoring-exporter:2.1.9
    imagePullPolicy: IfNotPresent
    configuration:
      metricsNameSnakeCase: true
      queries:
      - key: name
        keyName: location
        prefix: wls_server_
        applicationRuntimes:
          key: name
          keyName: app
          componentRuntimes:
            prefix: wls_webapp_config_
            type: WebAppComponentRuntime
            key: name
            values:
              - deploymentState
              - contextRoot
              - sourceInfo
              - sessionsOpenedTotalCount
              - openSessionsCurrentCount
              - openSessionsHighCount
            servlets:
              prefix: wls_servlet_
              key: servletName
      - JVMRuntime:
          prefix: wls_jvm_
          key: name
      - executeQueueRuntimes:
          prefix: wls_socketmuxer_
          key: name
          values:
            - pendingRequestCurrentCount
      - workManagerRuntimes:
          prefix: wls_workmanager_
          key: name
          values:
            - stuckThreadCount
            - pendingRequests
            - completedRequests
      - threadPoolRuntime:
          prefix: wls_threadpool_
          key: name
          values:
            - executeThreadTotalCount
            - queueLength
            - stuckThreadCount
            - hoggingThreadCount
      - JMSRuntime:
          key: name
          keyName: jmsruntime
          prefix: wls_jmsruntime_
          JMSServers:
            prefix: wls_jms_
            key: name
            keyName: jmsserver
            destinations:
              prefix: wls_jms_dest_
              key: name
              keyName: destination
      - persistentStoreRuntimes:
          prefix: wls_persistentstore_
          key: name
      - JDBCServiceRuntime:
          JDBCDataSourceRuntimeMBeans:
            prefix: wls_datasource_
            key: name
      - JTARuntime:
          prefix: wls_jta_
          key: name
  # Configuración de pods
  serverPod:
    env:
      - name: JAVA_OPTIONS
        value: >-
          -Dweblogic.StdoutDebugEnabled=false
          -Djava.security.egd=file:/dev/./urandom
          -Dweblogic.security.SSL.ignoreHostnameVerification=true
          -Dtangosol.coherence.cacheconfig=/coherenceclient/cache_config_client.xml
          -Dtangosol.coherence.override=/coherenceclient/tangosol-coherence-override.xml
          -Dtap.cache.config-file=/coherenceclient/cache_config_client.xml
          -Dtap.config-server.connection-string=zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local:2181
      - name: USER_MEM_ARGS
        value: '-Xms512m -Xmx1024m'
      - name: tap.config-server.connection-string
        value: 'zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local:2181'
      - name: tap.cache.config-file
        value: /coherenceclient/cache_config_client.xml
    volumeMounts:
      - mountPath: /coherenceclient
        name: coherence-vol
    volumes:
      - name: coherence-vol
        configMap:
          name: cache-config-client
  configuration:
    model:
      auxiliaryImages:
        - image: mad.ocir.io/axojlwfywuhi/oke/telco-wjms:v1.6
          imagePullPolicy: IfNotPresent
      domainType: WLS
      runtimeEncryptionSecret: wjms-runtime-encryption-secret
    secrets:
      - wjms-jdbc-ujms-tlcbam-ds
      - wjms-jdbc-ujms-tlcsig-ds
    introspectorJobActiveDeadlineSeconds: 900
  clusters:
    - name: wjms-wjmsjmswjms
    - name: wjms-wjmsjmscoco