apiVersion: v1
kind: Service
metadata:
  name: wjms-exporter
  namespace: wjms-ns
  labels:
    weblogic.domainUID: wjms
    app: weblogic-monitoring-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    weblogic.domainUID: wjms
